#ifndef HHGRADEDGABAAMECHANISM_META_H
#define HHGRADEDGABAAMECHANISM_META_H

#include "myriad_metaprogramming.h"

// Generics
#define HHGRADEDGABAAMECHANISM_OBJECT HHGradedGABAAMechanism
#define HHGRADEDGABAAMECHANISM_CLASS HHGradedGABAAMechanismClass

// Attributes
#define SUPERCLASS_HHGRADEDGABAAMECHANISM_OBJECT_NAME _
#define SUPERCLASS_HHGRADEDGABAAMECHANISM_CLASS_NAME _
#define HHGRADEDGABAAMECHANISM_SYNAPTIC_GATING g_s
#define HHGRADEDGABAAMECHANISM_SYNAPTIC_GATING_INIT g_s_init
#define HHGRADEDGABAAMECHANISM_SYNAPTIC_GATING_LENGTH g_s_len
#define HHGRADEDGABAAMECHANISM_MAX_SYN_CONDUCTANCE g_max
#define HHGRADEDGABAAMECHANISM_HALF_ACTIVATION_POTENTIAL theta
#define HHGRADEDGABAAMECHANISM_MAXIMAL_SLOPE sigma
#define HHGRADEDGABAAMECHANISM_CHANNEL_OPENING_TIME tau_alpha
#define HHGRADEDGABAAMECHANISM_CHANNEL_CLOSING_TIME tau_beta
#define HHGRADEDGABAAMECHANISM_REVERSAL_POTENTIAL gaba_rev

// Mechanism function
#define HHGRADEDGABAAMECHANISM_MECH_FXN_RET double
#define HHGRADEDGABAAMECHANISM_MECH_FXN_ARGS void* _self, \
	void* pre_comp, \
	void* post_comp, \
	const double dt, \
	const double global_time, \
	const unsigned int curr_step
#define HHGRADEDGABAAMECHANISM_MECH_FXN_NAME mech_fun





#endif
