#ifndef HHNACURRMECHANISM_META_H
#define HHNACURRMECHANISM_META_H

#include "myriad_metaprogramming.h"

// Generics
#define HHNACURRMECHANISM_OBJECT HHNaCurrMechanism
#define HHNACURRMECHANISM_CLASS HHNaCurrMechanismClass

// Attributes
#define SUPERCLASS_HHNACURRMECHANISM_OBJECT_NAME _
#define SUPERCLASS_HHNACURRMECHANISM_CLASS_NAME _
#define HHNACURRMECHANISM_CHANNEL_CONDUCTANCE g_na
#define HHNACURRMECHANISM_REVERSAL_POTENTIAL e_na
#define HHNACURRMECHANISM_HH_M hh_m
#define HHNACURRMECHANISM_HH_H hh_h

// Dynamic initialisation properties
#define HHNACURRMECHANISM_INIT_FXN_NAME initHHNaCurrMechanism


#endif
